apiVersion: v1
kind: Service
metadata:
  name: entity-sentiment-api
spec:
  selector:
    app: entity-sentiment-api
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: entity-sentiment-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: sentiment.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: entity-sentiment-api
            port:
              number: 80

